### ISSUE TITLE
Unable to reproduce results using FFST

### ISSUE THREAD

**Issue by fmiotello** [eliaszea/RIRIS#1]
Hi,

I'm trying to reproduce the results using the FFST toolbox, as suggested in the README. Unfortunately, it seems that the toolbox supports only square images, while the provided RIRs have different size dimensions (TxM).
Could you please explain me how to use FFST to compute the shearlet dictionary of rectangular images? 

Thank you

**Comment by eliaszea** [comment]
Hi Federico,

Thanks for reaching out. You should be able to run the code with the measurement data (non-square images) by using the shearlet functions in the repository. They are look-up tables in [RIRIS/dependencies/basisFunctions](https://github.com/eliaszea/RIRIS/tree/main/dependencies/basisFunctions) for 2, 3, 4, and 5 shearlet decomposition scales. However, to run the code with arbitrarily-sized images, you must create a shearlet system with the desired image dimensions. You can do this in Matlab using [cone-adapted bandlimited shearlet systems](https://www.mathworks.com/help/wavelet/ref/shearletsystem.html). I will add this comment in the README. 

All the best,
Elias
